export const enum ACCESSIBLE {
  WHEN_UNLOCKED = 0,
  AFTER_FIRST_UNLOCK = 1,
  ALWAYS = 2,
  WHEN_PASSCODE_SET_THIS_DEVICE_ONLY = 3,
  WHEN_UNLOCKED_THIS_DEVICE_ONLY = 4,
  AFTER_FIRST_UNLOCK_THIS_DEVICE_ONLY = 5,
  ALWAYS_THIS_DEVICE_ONLY = 6,
}
